site_name: Deezer

site_favicon: assets/favicon.ico

nav:
    - Inicial: index.md
    - Planejamento: planejamento.md
    - Pr√©-rastreabilidade:
        - Rich Pictures: pre-rastreabilidade/rich-pictures.md

theme: journal

extra_css:
    - 'stylesheets/common.css'